Update Libraries, Add /healthz endpoint
missionlane/prometheus-mailgun-exporter pull request #5
Opened 2021-08-13 14:39 UTC by cpressland

Update all Libraries to latest versions, add a /healthz endpoint. Replaced logging library with zerolog as `github.com/prometheus/common/log` has since been removed.

2021-09-10 18:05 UTC, xbglowx commented
Sorry, just noticed this. I will take a look.

2021-09-29 13:49 UTC, xbglowx requested changes
I believe you will need call Msg or Msgf in order for fatal to work properly and exit. For example, as is, if you don't specify environment variable `MG_API_KEY`, it will not exit. 

The screenshot was taken from [here](https://pkg.go.dev/github.com/rs/zerolog/log@v1.23.0#Fatal)

<img width="739" alt="Screen Shot 2021-09-29 at 9 46 54 AM" src="https://user-images.githubusercontent.com/1020898/135281295-332a3998-ed36-4cee-8086-10c528e14aaa.png">

Replacing `log.Fatal().Err(err)` with `log.Fatal().Err(err).Msgf("%v", err)` should work.

2021-09-29 13:49 UTC, xbglowx commented on VERSION
> +0.0.6
Can you please leave this out. I will update once I am ready to cut a new release.

2021-10-04 08:27 UTC, cpressland commented
Requested changes made, let me know if you want anything else.

2021-10-05 14:13 UTC, merged

2021-10-20 15:44 UTC, Muhammadmohid commented
can you please give me a guide how to add my domain and do i have to add my api key? and how to add those kindly change the main guide